### PR TITLE
Add Storybook, typescript, prettier

### PR DESCRIPTION
**Pull request by vikramk0901**
This PR adds storybook, typescript, prettier.

To test this.
`yarn install`
`yarn storybook`

- [ ] Documentation updates.
- [ ] Unit tests fixes.
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checks

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vikramk0901** [comment]
Added story book and modified folder structure. You can arrange it the way you like it.
For some reason eslint is failing. I will take a look when i get a chance if not you can go ahead and try it.

**Comment by VJAI** [comment]
I'm happy with the PR overall :) There may be some minor tweaking we need to do but that's ok. I'm merging it. Will download the code in my machine and do some more testing!

**Comment by vikramk0901** [comment]
ya try to enable es lint and also add build set up too.

**Comment by vikramk0901** [comment]
np. same here. Catch you on the weekend.

**Pull request merged**
