### PR TITLE
Add typescript, eslint, prettier etc

### PR DESCRIPTION
**Pull request by vikramk0901**
## ESLint, Typescript, Prettier
This PR adds the above mentioned plugins. 

- [ ] Documentation updates.
- [ ] Unit tests fixes.
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checks

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vikramk0901** [comment]
@vanand-conga Take a look and let me know if you are ok with all this.

**Comment by vikramk0901** [comment]
There is some issue with webpack. I might have messed it up. I will raise another pr again.

**Comment by vikramk0901** [comment]
I think most of the webpack loaders are a bit older versions. You ok if i upgrade them?

**Comment by VJAI** [comment]
@vikramk0901 I'm ok with upgrading typescript. Let me create a separate branch for you, once everything is good and nice we can merge to main.

**Comment by VJAI** [comment]
Create the PR for typescript changes in this branch https://github.com/VJAI/tiny/tree/typescript. You can upgrade webpack as well. In fact let's update all the npm packages.

**Comment by vikramk0901** [comment]
Ok. will do.

**Pull request closed without merging**
